<?php

declare(strict_types=1);

namespace ItechWorld\SuluTailwindThemeBundle\DataFixtures;

/**
 * Provides preset theme data for the 6 built-in themes.
 *
 * Each preset contains complete design tokens (colors, typography, borders,
 * buttons, block variants), menu configuration, and block styles for all
 * 8 block types.
 *
 * Button property names match the admin form fields:
 *   bg, text, border, hoverBg, hoverText, hoverBorder, radius
 *
 * Border/button radius values use Tailwind class names (e.g. "rounded-lg")
 * which are resolved to CSS values by the ThemeCompiler.
 *
 * Typography families use internal names:
 *   name, role, source, fallback
 *
 * Typography assignments use 5 properties per element:
 *   family, weight, size, style, lineHeight
 *
 * Block variants use indexed arrays (position 0, 1, 2) with properties:
 *   label, title, subtitle, paragraph, link, list, hr, paragraphBg, blockBg,
 *   buttonStyle, formBg, formText, formLabel, formPlaceholder, formBorder,
 *   formBorderFocus, formBorderError
 */
class ThemeFixtures
{
    /**
     * Get all available theme presets.
     *
     * @return array<string, array<string, mixed>> Keyed by theme name
     */
    public static function getPresets(): array
    {
        return [
            'corporate' => self::getCorporatePreset(),
            'creative' => self::getCreativePreset(),
            'minimal' => self::getMinimalPreset(),
            'nature' => self::getNaturePreset(),
            'halloween' => self::getHalloweenPreset(),
            'christmas' => self::getChristmasPreset(),
            'megamenu' => self::getMegamenuPreset(),
        ];
    }

    /**
     * Corporate theme: professional blues, Inter font, rounded-lg radius.
     *
     * @return array<string, mixed>
     */
    private static function getCorporatePreset(): array
    {
        return [
            'name' => 'corporate',
            'label' => 'Corporate Professional',
            'tokens' => [
                'colors' => [
                    'primary' => '#1a56db',
                    'secondary' => '#475569',
                    'accent' => '#F59E0B',
                    'background' => '#ffffff',
                    'text' => 'ref:secondary-950',
                    'link' => 'ref:primary-700',
                    'linkHover' => 'ref:primary-800',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Inter',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                        [
                            'name' => 'Inter',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '1.875rem',
                        '4xl' => '2.25rem',
                        '5xl' => '3rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '700', 'size' => '2.5rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h2' => ['family' => 'heading', 'weight' => '600', 'size' => '2rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h3' => ['family' => 'heading', 'weight' => '600', 'size' => '1.5rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h4' => ['family' => 'heading', 'weight' => '500', 'size' => '1.25rem', 'style' => 'normal', 'lineHeight' => '1.35'],
                        'h5' => ['family' => 'heading', 'weight' => '500', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'heading', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                        'link' => ['family' => 'body', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-lg',
                    'radiusSm' => 'rounded-sm',
                    'radiusLg' => 'rounded-xl',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-lg',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1.5rem',
                        'paddingY' => '0.75rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-700',
                        'text' => 'ref:secondary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-800',
                        'hoverText' => 'ref:secondary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'sm',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'secondary' => [
                        'bg' => 'ref:secondary-50',
                        'text' => 'ref:primary-700',
                        'border' => 'ref:primary-700',
                        'hoverBg' => 'ref:secondary-50',
                        'hoverText' => 'ref:primary-800',
                        'hoverBorder' => 'ref:primary-800',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'sm',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'accent' => [
                        'bg' => 'ref:accent-500',
                        'text' => 'ref:secondary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:accent-500',
                        'hoverText' => 'ref:secondary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'md',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Clair',
                        'title' => 'ref:secondary-950',
                        'subtitle' => 'ref:secondary-800',
                        'paragraph' => 'ref:secondary-800',
                        'link' => 'ref:primary-700',
                        'list' => 'ref:secondary-800',
                        'hr' => 'ref:secondary-100',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:secondary-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:secondary-50',
                        'formText' => 'ref:secondary-800',
                        'formLabel' => 'ref:secondary-950',
                        'formPlaceholder' => 'ref:secondary-400',
                        'formBorder' => 'ref:secondary-200',
                        'formBorderFocus' => 'ref:primary-700',
                        'formBorderError' => 'ref:accent-400',
                    ],
                    [
                        'label' => 'Accent primaire',
                        'title' => 'ref:secondary-50',
                        'subtitle' => 'ref:primary-100',
                        'paragraph' => 'ref:primary-100',
                        'link' => 'ref:secondary-50',
                        'list' => 'ref:primary-100',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'rgba(255,255,255,0.08)',
                        'blockBg' => 'ref:primary-700',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-100',
                        'formLabel' => 'ref:secondary-50',
                        'formPlaceholder' => 'ref:primary-100',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:secondary-50',
                        'formBorderError' => 'ref:accent-300',
                    ],
                    [
                        'label' => 'Sombre',
                        'title' => 'ref:secondary-50',
                        'subtitle' => 'ref:secondary-200',
                        'paragraph' => 'ref:secondary-200',
                        'link' => 'ref:primary-400',
                        'list' => 'ref:secondary-200',
                        'hr' => 'ref:secondary-900',
                        'paragraphBg' => 'ref:secondary-950',
                        'blockBg' => 'ref:secondary-950',
                        'buttonStyle' => 'accent',
                        'formBg' => 'ref:secondary-950',
                        'formText' => 'ref:secondary-200',
                        'formLabel' => 'ref:secondary-50',
                        'formPlaceholder' => 'ref:secondary-200',
                        'formBorder' => 'ref:secondary-900',
                        'formBorderFocus' => 'ref:primary-400',
                        'formBorderError' => 'ref:accent-400',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'none',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => true,
                'childLevels' => 3,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => false,
                'displaySocialMedia' => false,
                'colors' => [
                    'bg' => '#ffffff',
                    'text' => 'ref:secondary-950',
                    'textHover' => '#1a56db',
                    'secondBg' => '#f8fafc',
                    'secondText' => '#475569',
                    'secondTextHover' => '#1a56db',
                    'thirdBg' => '#f1f5f9',
                    'thirdText' => '#64748b',
                    'divider' => '#e2e8f0',
                    'burgerOpen' => '#1e293b',
                    'burgerClose' => '#ffffff',
                    'socialMedia' => '#94a3b8',
                    'socialMediaHover' => '#1a56db',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Creative theme: pink + amber, Poppins/DM Sans, rounded-2xl radius, bold.
     *
     * @return array<string, mixed>
     */
    private static function getCreativePreset(): array
    {
        return [
            'name' => 'creative',
            'label' => 'Creative Bold',
            'tokens' => [
                'colors' => [
                    'primary' => '#ec4899',
                    'secondary' => '#f59e0b',
                    'accent' => '#EC4899',
                    'background' => '#fffbeb',
                    'text' => 'ref:background-950',
                    'link' => 'ref:primary-500',
                    'linkHover' => 'ref:primary-600',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Poppins',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                        [
                            'name' => 'DM Sans',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '2rem',
                        '4xl' => '2.5rem',
                        '5xl' => '3.5rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '800', 'size' => '3rem', 'style' => 'normal', 'lineHeight' => '1.15'],
                        'h2' => ['family' => 'heading', 'weight' => '700', 'size' => '2.25rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h3' => ['family' => 'heading', 'weight' => '700', 'size' => '1.75rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h4' => ['family' => 'heading', 'weight' => '600', 'size' => '1.375rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h5' => ['family' => 'heading', 'weight' => '600', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.35'],
                        'h6' => ['family' => 'heading', 'weight' => '600', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                        'link' => ['family' => 'body', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-2xl',
                    'radiusSm' => 'rounded-lg',
                    'radiusLg' => 'rounded-3xl',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-2xl',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '2rem',
                        'paddingY' => '1rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-500',
                        'text' => 'ref:primary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-600',
                        'hoverText' => 'ref:primary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-2xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-primary',
                        'hoverTransform' => 'pop',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '500ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'gradient-shift',
                    ],
                    'secondary' => [
                        'bg' => 'ref:secondary-500',
                        'text' => 'ref:background-950',
                        'border' => 'none',
                        'hoverBg' => 'ref:secondary-700',
                        'hoverText' => 'ref:background-950',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-2xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-secondary',
                        'hoverTransform' => 'lift-strong',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'slide-right',
                    ],
                    'accent' => [
                        'bg' => 'ref:background-400',
                        'text' => 'ref:primary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-600',
                        'hoverText' => 'ref:primary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-2xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-accent',
                        'hoverTransform' => 'skew',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '500ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'slide-up',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Clair',
                        'title' => 'ref:background-950',
                        'subtitle' => 'ref:background-600',
                        'paragraph' => 'ref:background-600',
                        'link' => 'ref:primary-500',
                        'list' => 'ref:background-600',
                        'hr' => 'ref:secondary-300',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:secondary-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:primary-50',
                        'formText' => 'ref:background-600',
                        'formLabel' => 'ref:background-950',
                        'formPlaceholder' => 'ref:background-400',
                        'formBorder' => 'ref:background-200',
                        'formBorderFocus' => 'ref:primary-500',
                        'formBorderError' => 'ref:primary-600',
                    ],
                    [
                        'label' => 'Accent rose',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:primary-100',
                        'paragraph' => 'ref:primary-100',
                        'link' => 'ref:secondary-400',
                        'list' => 'ref:primary-100',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'rgba(255,255,255,0.08)',
                        'blockBg' => 'ref:primary-500',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-100',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:primary-100',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:primary-50',
                        'formBorderError' => 'ref:primary-300',
                    ],
                    [
                        'label' => 'Sombre',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:background-200',
                        'paragraph' => 'ref:background-200',
                        'link' => 'ref:primary-400',
                        'list' => 'ref:background-200',
                        'hr' => 'ref:background-900',
                        'paragraphBg' => 'ref:background-950',
                        'blockBg' => 'ref:background-950',
                        'buttonStyle' => 'accent',
                        'formBg' => 'ref:background-950',
                        'formText' => 'ref:background-200',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:background-200',
                        'formBorder' => 'ref:background-900',
                        'formBorderFocus' => 'ref:primary-400',
                        'formBorderError' => 'ref:primary-500',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'fade',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => false,
                'childLevels' => 2,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => true,
                'displaySocialMedia' => true,
                'colors' => [
                    'bg' => '#ffffff',
                    'text' => 'ref:background-950',
                    'textHover' => '#ec4899',
                    'secondBg' => '#fdf2f8',
                    'secondText' => '#6b7280',
                    'secondTextHover' => '#ec4899',
                    'thirdBg' => '#fce7f3',
                    'thirdText' => '#9ca3af',
                    'divider' => '#fde68a',
                    'burgerOpen' => '#1f2937',
                    'burgerClose' => '#ffffff',
                    'socialMedia' => '#9ca3af',
                    'socialMediaHover' => '#ec4899',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Minimal theme: black/white, Playfair Display/Inter, no radius, clean.
     *
     * @return array<string, mixed>
     */
    private static function getMinimalPreset(): array
    {
        return [
            'name' => 'minimal',
            'label' => 'Minimal Clean',
            'tokens' => [
                'colors' => [
                    'primary' => '#000000',
                    'secondary' => '#6b7280',
                    'accent' => '#6366F1',
                    'background' => '#ffffff',
                    'text' => 'ref:primary-950',
                    'link' => 'ref:primary-950',
                    'linkHover' => 'ref:secondary-900',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Playfair Display',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'Georgia, serif',
                        ],
                        [
                            'name' => 'Inter',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '1.875rem',
                        '4xl' => '2.25rem',
                        '5xl' => '3rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '700', 'size' => '2.5rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h2' => ['family' => 'heading', 'weight' => '700', 'size' => '2rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h3' => ['family' => 'heading', 'weight' => '400', 'size' => '1.5rem', 'style' => 'italic', 'lineHeight' => '1.3'],
                        'h4' => ['family' => 'heading', 'weight' => '400', 'size' => '1.25rem', 'style' => 'italic', 'lineHeight' => '1.35'],
                        'h5' => ['family' => 'body', 'weight' => '400', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '300', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.8'],
                        'link' => ['family' => 'body', 'weight' => '400', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.8'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-none',
                    'radiusSm' => 'rounded-none',
                    'radiusLg' => 'rounded-none',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-none',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1rem',
                        'paddingY' => '0.5rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-950',
                        'text' => 'ref:accent-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:secondary-900',
                        'hoverText' => 'ref:accent-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-none',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'none',
                        'hoverTransform' => 'none',
                        'hoverOpacity' => '0.9',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'secondary' => [
                        'bg' => 'ref:accent-50',
                        'text' => 'ref:primary-950',
                        'border' => 'ref:primary-950',
                        'hoverBg' => 'ref:background-50',
                        'hoverText' => 'ref:primary-950',
                        'hoverBorder' => 'ref:primary-950',
                        'radius' => 'rounded-none',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'none',
                        'hoverTransform' => 'none',
                        'hoverOpacity' => '0.9',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'accent' => [
                        'bg' => 'ref:primary-600',
                        'text' => 'ref:accent-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:background-800',
                        'hoverText' => 'ref:accent-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-none',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'none',
                        'hoverTransform' => 'none',
                        'hoverOpacity' => '0.9',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Clair',
                        'title' => 'ref:primary-950',
                        'subtitle' => 'ref:primary-600',
                        'paragraph' => 'ref:primary-600',
                        'link' => 'ref:primary-950',
                        'list' => 'ref:primary-600',
                        'hr' => 'ref:primary-100',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:accent-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:accent-50',
                        'formText' => 'ref:primary-600',
                        'formLabel' => 'ref:primary-950',
                        'formPlaceholder' => 'ref:primary-400',
                        'formBorder' => 'ref:secondary-200',
                        'formBorderFocus' => 'ref:primary-950',
                        'formBorderError' => 'ref:primary-600',
                    ],
                    [
                        'label' => 'Gris neutre',
                        'title' => 'ref:primary-950',
                        'subtitle' => 'ref:background-800',
                        'paragraph' => 'ref:background-800',
                        'link' => 'ref:primary-950',
                        'list' => 'ref:background-800',
                        'hr' => 'ref:primary-200',
                        'paragraphBg' => 'ref:background-50',
                        'blockBg' => 'ref:primary-50',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'ref:accent-50',
                        'formText' => 'ref:background-800',
                        'formLabel' => 'ref:primary-950',
                        'formPlaceholder' => 'ref:primary-400',
                        'formBorder' => 'ref:primary-200',
                        'formBorderFocus' => 'ref:primary-950',
                        'formBorderError' => 'ref:primary-600',
                    ],
                    [
                        'label' => 'Sombre',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:primary-400',
                        'paragraph' => 'ref:primary-400',
                        'link' => 'ref:primary-100',
                        'list' => 'ref:primary-400',
                        'hr' => 'ref:primary-900',
                        'paragraphBg' => 'ref:primary-950',
                        'blockBg' => 'ref:primary-950',
                        'buttonStyle' => 'accent',
                        'formBg' => 'ref:primary-950',
                        'formText' => 'ref:primary-400',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:primary-400',
                        'formBorder' => 'ref:primary-900',
                        'formBorderFocus' => 'ref:primary-100',
                        'formBorderError' => 'ref:primary-400',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'none',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => true,
                'childLevels' => 2,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => false,
                'displaySocialMedia' => false,
                'colors' => [
                    'bg' => '#ffffff',
                    'text' => 'ref:primary-950',
                    'textHover' => '#000000',
                    'secondBg' => '#fafafa',
                    'secondText' => '#737373',
                    'secondTextHover' => '#000000',
                    'thirdBg' => '#f5f5f5',
                    'thirdText' => '#a3a3a3',
                    'divider' => '#e5e5e5',
                    'burgerOpen' => '#111111',
                    'burgerClose' => '#ffffff',
                    'socialMedia' => '#a3a3a3',
                    'socialMediaHover' => '#000000',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Nature theme: forest green + gold, DM Sans/Open Sans, rounded-xl radius.
     *
     * @return array<string, mixed>
     */
    private static function getNaturePreset(): array
    {
        return [
            'name' => 'nature',
            'label' => 'Nature Organic',
            'tokens' => [
                'colors' => [
                    'primary' => '#065f46',
                    'secondary' => '#d97706',
                    'accent' => '#F97316',
                    'background' => '#fefdf8',
                    'text' => 'ref:primary-950',
                    'link' => 'ref:primary-800',
                    'linkHover' => 'ref:primary-700',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'DM Sans',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                        [
                            'name' => 'Open Sans',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '1.875rem',
                        '4xl' => '2.25rem',
                        '5xl' => '3rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '700', 'size' => '2.5rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h2' => ['family' => 'heading', 'weight' => '600', 'size' => '2rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h3' => ['family' => 'heading', 'weight' => '600', 'size' => '1.5rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h4' => ['family' => 'heading', 'weight' => '500', 'size' => '1.25rem', 'style' => 'normal', 'lineHeight' => '1.35'],
                        'h5' => ['family' => 'heading', 'weight' => '500', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'heading', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                        'link' => ['family' => 'body', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-xl',
                    'radiusSm' => 'rounded-md',
                    'radiusLg' => 'rounded-2xl',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-xl',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1.5rem',
                        'paddingY' => '0.75rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-800',
                        'text' => 'ref:background-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-900',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'lg',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '500ms',
                        'hoverEasing' => 'ease-in-out',
                    ],
                    'secondary' => [
                        'bg' => 'ref:accent-500',
                        'text' => 'ref:background-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:secondary-600',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'md',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '500ms',
                        'hoverEasing' => 'ease-in-out',
                    ],
                    'accent' => [
                        'bg' => 'ref:primary-700',
                        'text' => 'ref:background-50',
                        'border' => 'ref:primary-700',
                        'hoverBg' => 'ref:primary-700',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'ref:primary-800',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'lg',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '500ms',
                        'hoverEasing' => 'ease-in-out',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Clair nature',
                        'title' => 'ref:primary-950',
                        'subtitle' => 'ref:primary-700',
                        'paragraph' => 'ref:primary-700',
                        'link' => 'ref:primary-800',
                        'list' => 'ref:primary-700',
                        'hr' => 'ref:primary-200',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:background-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:background-50',
                        'formText' => 'ref:primary-700',
                        'formLabel' => 'ref:primary-950',
                        'formPlaceholder' => 'ref:background-500',
                        'formBorder' => 'ref:primary-200',
                        'formBorderFocus' => 'ref:primary-800',
                        'formBorderError' => 'ref:accent-500',
                    ],
                    [
                        'label' => 'Accent vert',
                        'title' => 'ref:background-50',
                        'subtitle' => 'ref:primary-300',
                        'paragraph' => 'ref:primary-300',
                        'link' => 'ref:accent-400',
                        'list' => 'ref:primary-300',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'rgba(255,255,255,0.08)',
                        'blockBg' => 'ref:primary-800',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-300',
                        'formLabel' => 'ref:background-50',
                        'formPlaceholder' => 'ref:primary-300',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:background-50',
                        'formBorderError' => 'ref:accent-300',
                    ],
                    [
                        'label' => 'Sombre foret',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:primary-300',
                        'paragraph' => 'ref:primary-300',
                        'link' => 'ref:primary-500',
                        'list' => 'ref:primary-300',
                        'hr' => 'ref:primary-900',
                        'paragraphBg' => 'ref:primary-950',
                        'blockBg' => 'ref:primary-900',
                        'buttonStyle' => 'accent',
                        'formBg' => 'ref:primary-950',
                        'formText' => 'ref:primary-300',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:primary-300',
                        'formBorder' => 'ref:primary-900',
                        'formBorderFocus' => 'ref:primary-500',
                        'formBorderError' => 'ref:accent-400',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'slide',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => true,
                'childLevels' => 3,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => true,
                'displaySocialMedia' => true,
                'colors' => [
                    'bg' => '#fefdf8',
                    'text' => 'ref:primary-950',
                    'textHover' => '#065f46',
                    'secondBg' => '#ecfdf5',
                    'secondText' => '#4d7c4d',
                    'secondTextHover' => '#065f46',
                    'thirdBg' => '#d1fae5',
                    'thirdText' => '#6b7280',
                    'divider' => '#d1e7dd',
                    'burgerOpen' => '#1a2e1a',
                    'burgerClose' => '#ffffff',
                    'socialMedia' => '#4d7c4d',
                    'socialMediaHover' => '#065f46',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Halloween theme: orange/purple/black, Creepster/Nunito Sans, rounded-xl radius, spooky.
     *
     * @return array<string, mixed>
     */
    private static function getHalloweenPreset(): array
    {
        return [
            'name' => 'halloween',
            'label' => 'Halloween Spooky',
            'tokens' => [
                'colors' => [
                    'primary' => '#f97316',
                    'secondary' => '#7c3aed',
                    'accent' => '#eab308',
                    'background' => '#1c1917',
                    'text' => 'ref:background-50',
                    'link' => 'ref:primary-500',
                    'linkHover' => 'ref:primary-400',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Creepster',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'cursive, system-ui',
                        ],
                        [
                            'name' => 'Nunito Sans',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '2rem',
                        '4xl' => '2.75rem',
                        '5xl' => '3.5rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '400', 'size' => '3rem', 'style' => 'normal', 'lineHeight' => '1.15'],
                        'h2' => ['family' => 'heading', 'weight' => '400', 'size' => '2.25rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h3' => ['family' => 'heading', 'weight' => '400', 'size' => '1.75rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h4' => ['family' => 'heading', 'weight' => '400', 'size' => '1.375rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h5' => ['family' => 'body', 'weight' => '600', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'body', 'weight' => '600', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                        'link' => ['family' => 'body', 'weight' => '600', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-xl',
                    'radiusSm' => 'rounded-md',
                    'radiusLg' => 'rounded-2xl',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-xl',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1.5rem',
                        'paddingY' => '0.75rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-500',
                        'text' => 'ref:background-950',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-700',
                        'hoverText' => 'ref:background-950',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '2px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-pulse-primary',
                        'hoverTransform' => 'tilt',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'pulse-bg',
                    ],
                    'secondary' => [
                        'bg' => 'ref:secondary-600',
                        'text' => 'ref:secondary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:secondary-700',
                        'hoverText' => 'ref:secondary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '2px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-secondary',
                        'hoverTransform' => 'lift-strong',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'slide-left',
                    ],
                    'accent' => [
                        'bg' => 'ref:accent-500',
                        'text' => 'ref:background-950',
                        'border' => 'none',
                        'hoverBg' => 'ref:accent-700',
                        'hoverText' => 'ref:background-950',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '2px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-pulse-accent',
                        'hoverTransform' => 'scale-up',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'bounce',
                        'hoverBgEffect' => 'none',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Nuit noire',
                        'title' => 'ref:primary-500',
                        'subtitle' => 'ref:background-400',
                        'paragraph' => 'ref:background-200',
                        'link' => 'ref:primary-500',
                        'list' => 'ref:background-200',
                        'hr' => 'ref:background-900',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:background-950',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:background-950',
                        'formText' => 'ref:background-200',
                        'formLabel' => 'ref:primary-500',
                        'formPlaceholder' => 'ref:background-400',
                        'formBorder' => 'ref:background-900',
                        'formBorderFocus' => 'ref:primary-500',
                        'formBorderError' => 'ref:primary-400',
                    ],
                    [
                        'label' => 'Citrouille',
                        'title' => 'ref:background-950',
                        'subtitle' => 'ref:primary-950',
                        'paragraph' => 'ref:primary-950',
                        'link' => 'ref:secondary-600',
                        'list' => 'ref:primary-950',
                        'hr' => 'rgba(0,0,0,0.15)',
                        'paragraphBg' => 'rgba(0,0,0,0.05)',
                        'blockBg' => 'ref:primary-500',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-950',
                        'formLabel' => 'ref:background-950',
                        'formPlaceholder' => 'ref:primary-950',
                        'formBorder' => 'rgba(0,0,0,0.15)',
                        'formBorderFocus' => 'ref:secondary-600',
                        'formBorderError' => 'ref:primary-300',
                    ],
                    [
                        'label' => 'Violet sorcier',
                        'title' => 'ref:secondary-50',
                        'subtitle' => 'ref:secondary-300',
                        'paragraph' => 'ref:secondary-200',
                        'link' => 'ref:primary-500',
                        'list' => 'ref:secondary-200',
                        'hr' => 'rgba(255,255,255,0.15)',
                        'paragraphBg' => 'rgba(255,255,255,0.06)',
                        'blockBg' => 'ref:secondary-800',
                        'buttonStyle' => 'accent',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:secondary-200',
                        'formLabel' => 'ref:secondary-50',
                        'formPlaceholder' => 'ref:secondary-300',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:secondary-50',
                        'formBorderError' => 'ref:primary-300',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'fade',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => true,
                'childLevels' => 2,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => true,
                'displaySocialMedia' => false,
                'colors' => [
                    'bg' => '#1c1917',
                    'text' => 'ref:background-50',
                    'textHover' => '#f97316',
                    'secondBg' => '#292524',
                    'secondText' => '#a8a29e',
                    'secondTextHover' => '#f97316',
                    'thirdBg' => '#44403c',
                    'thirdText' => '#d6d3d1',
                    'divider' => '#44403c',
                    'burgerOpen' => '#f97316',
                    'burgerClose' => '#f97316',
                    'socialMedia' => '#a8a29e',
                    'socialMediaHover' => '#f97316',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Christmas theme: red/green/gold, Mountains of Christmas/Source Sans 3, rounded-xl radius, festive.
     *
     * @return array<string, mixed>
     */
    private static function getChristmasPreset(): array
    {
        return [
            'name' => 'christmas',
            'label' => 'Christmas Festive',
            'tokens' => [
                'colors' => [
                    'primary' => '#dc2626',
                    'secondary' => '#15803d',
                    'accent' => '#d97706',
                    'background' => '#fef2f2',
                    'text' => 'ref:background-950',
                    'link' => 'ref:primary-600',
                    'linkHover' => 'ref:primary-700',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Mountains of Christmas',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'cursive, Georgia, serif',
                        ],
                        [
                            'name' => 'Source Sans 3',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '2rem',
                        '4xl' => '2.5rem',
                        '5xl' => '3.25rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '700', 'size' => '2.75rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h2' => ['family' => 'heading', 'weight' => '700', 'size' => '2.25rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h3' => ['family' => 'heading', 'weight' => '400', 'size' => '1.75rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h4' => ['family' => 'heading', 'weight' => '400', 'size' => '1.375rem', 'style' => 'normal', 'lineHeight' => '1.35'],
                        'h5' => ['family' => 'body', 'weight' => '600', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'body', 'weight' => '600', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                        'link' => ['family' => 'body', 'weight' => '600', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.7'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-xl',
                    'radiusSm' => 'rounded-md',
                    'radiusLg' => 'rounded-xl',
                    'radiusFull' => 'rounded-full',
                    'imageRadius' => 'rounded-xl',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1.5rem',
                        'paddingY' => '0.75rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-600',
                        'text' => 'ref:background-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-700',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-primary',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                        'hoverBgEffect' => 'slide-right',
                    ],
                    'secondary' => [
                        'bg' => 'ref:secondary-700',
                        'text' => 'ref:background-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:secondary-800',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'md',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                        'hoverBgEffect' => 'none',
                    ],
                    'accent' => [
                        'bg' => 'ref:accent-500',
                        'text' => 'ref:background-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:accent-700',
                        'hoverText' => 'ref:background-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-xl',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'glow-pulse-accent',
                        'hoverTransform' => 'lift-strong',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                        'hoverBgEffect' => 'pulse-bg',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Neige',
                        'title' => 'ref:primary-800',
                        'subtitle' => 'ref:background-800',
                        'paragraph' => 'ref:background-900',
                        'link' => 'ref:primary-600',
                        'list' => 'ref:background-900',
                        'hr' => 'ref:primary-200',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:primary-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:background-50',
                        'formText' => 'ref:background-900',
                        'formLabel' => 'ref:primary-800',
                        'formPlaceholder' => 'ref:background-600',
                        'formBorder' => 'ref:primary-200',
                        'formBorderFocus' => 'ref:primary-600',
                        'formBorderError' => 'ref:primary-500',
                    ],
                    [
                        'label' => 'Sapin',
                        'title' => 'ref:background-50',
                        'subtitle' => 'ref:secondary-200',
                        'paragraph' => 'ref:secondary-100',
                        'link' => 'ref:accent-400',
                        'list' => 'ref:secondary-100',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'rgba(255,255,255,0.08)',
                        'blockBg' => 'ref:secondary-700',
                        'buttonStyle' => 'accent',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:secondary-100',
                        'formLabel' => 'ref:background-50',
                        'formPlaceholder' => 'ref:secondary-200',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:background-50',
                        'formBorderError' => 'ref:primary-300',
                    ],
                    [
                        'label' => 'Rouge festif',
                        'title' => 'ref:background-50',
                        'subtitle' => 'ref:primary-200',
                        'paragraph' => 'ref:primary-100',
                        'link' => 'ref:accent-400',
                        'list' => 'ref:primary-100',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'rgba(255,255,255,0.06)',
                        'blockBg' => 'ref:primary-600',
                        'buttonStyle' => 'secondary',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-100',
                        'formLabel' => 'ref:background-50',
                        'formPlaceholder' => 'ref:primary-200',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:background-50',
                        'formBorderError' => 'ref:primary-300',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'navbar',
                'animation' => 'slide',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => true,
                'childLevels' => 3,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => true,
                'displaySocialMedia' => true,
                'colors' => [
                    'bg' => '#fef2f2',
                    'text' => 'ref:background-950',
                    'textHover' => '#dc2626',
                    'secondBg' => '#fee2e2',
                    'secondText' => '#57534e',
                    'secondTextHover' => '#dc2626',
                    'thirdBg' => '#fecaca',
                    'thirdText' => '#78716c',
                    'divider' => '#fecaca',
                    'burgerOpen' => '#dc2626',
                    'burgerClose' => '#ffffff',
                    'socialMedia' => '#dc2626',
                    'socialMediaHover' => '#15803d',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }

    /**
     * Get default block styles for all 8 block types.
     *
     * Each block type has a default template and multiple style options
     * with their own templates.
     *
     * @return array<string, array<string, mixed>>
     */
    private static function getDefaultBlockStyles(): array
    {
        return [
            'text' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'centered', 'label' => 'Centre', 'twig' => '_style_centered.html.twig', 'default' => true],
                    ['key' => 'left_aligned', 'label' => 'Aligne gauche', 'twig' => '_style_left_aligned.html.twig'],
                    ['key' => 'two_columns', 'label' => 'Deux colonnes', 'twig' => '_style_two_columns.html.twig'],
                ],
            ],
            'text_images' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'classic', 'label' => 'Classique', 'twig' => '_style_classic.html.twig', 'default' => true],
                    ['key' => 'overlay', 'label' => 'Superpose', 'twig' => '_style_overlay.html.twig'],
                    ['key' => 'fullwidth', 'label' => 'Pleine largeur', 'twig' => '_style_fullwidth.html.twig'],
                    ['key' => 'mosaic', 'label' => 'Mosaique', 'twig' => '_style_mosaic.html.twig'],
                    ['key' => 'sidebar', 'label' => 'Bande laterale', 'twig' => '_style_sidebar.html.twig'],
                ],
            ],
            'gallery' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'grid', 'label' => 'Grille', 'twig' => '_style_grid.html.twig', 'default' => true],
                    ['key' => 'masonry', 'label' => 'Masonry', 'twig' => '_style_masonry.html.twig'],
                    ['key' => 'slider', 'label' => 'Slider', 'twig' => '_style_slider.html.twig'],
                    ['key' => 'carousel', 'label' => 'Carrousel', 'twig' => '_style_carousel.html.twig'],
                    ['key' => 'fullscreen_slider', 'label' => 'Slider plein ecran', 'twig' => '_style_fullscreen_slider.html.twig'],
                ],
            ],
            'key_figures' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'inline', 'label' => 'En ligne', 'twig' => '_style_inline.html.twig', 'default' => true],
                    ['key' => 'with_icons', 'label' => 'Avec icones', 'twig' => '_style_with_icons.html.twig'],
                    ['key' => 'grid_2x2', 'label' => 'Grille 2x2', 'twig' => '_style_grid_2x2.html.twig'],
                ],
            ],
            'linked_pages' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'cards', 'label' => 'Cartes', 'twig' => '_style_cards.html.twig', 'default' => true],
                    ['key' => 'list', 'label' => 'Liste', 'twig' => '_style_list.html.twig'],
                    ['key' => 'minimal', 'label' => 'Minimal', 'twig' => '_style_minimal.html.twig'],
                ],
            ],
            'location' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'map_only', 'label' => 'Carte seule', 'twig' => '_style_map_only.html.twig', 'default' => true],
                    ['key' => 'map_with_info', 'label' => 'Carte + infos', 'twig' => '_style_map_with_info.html.twig'],
                ],
            ],
            'form' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'centered', 'label' => 'Centre', 'twig' => '_style_centered.html.twig', 'default' => true],
                    ['key' => 'split', 'label' => 'Avec image', 'twig' => '_style_split.html.twig'],
                ],
            ],
            'document' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'default', 'label' => 'Par defaut', 'twig' => '_style_default.html.twig', 'default' => true],
                ],
            ],
            'grid' => [
                'enabled' => true,
                'styles' => [
                    ['key' => 'two_columns', 'label' => '2 Colonnes', 'twig' => '_style_two_columns.html.twig', 'default' => true],
                    ['key' => 'three_columns', 'label' => '3 Colonnes', 'twig' => '_style_three_columns.html.twig'],
                    ['key' => 'four_columns', 'label' => '4 Colonnes', 'twig' => '_style_four_columns.html.twig'],
                ],
            ],
        ];
    }

    /**
     * Mega menu theme: professional dark navbar with mega dropdown navigation.
     *
     * Uses the megamenu type in native mode (page tree) by default.
     *
     * @return array<string, mixed>
     */
    private static function getMegamenuPreset(): array
    {
        return [
            'name' => 'megamenu',
            'label' => 'Mega Menu Professional',
            'tokens' => [
                'colors' => [
                    'primary' => '#6366f1',
                    'secondary' => '#475569',
                    'accent' => '#f59e0b',
                    'background' => '#ffffff',
                    'text' => 'ref:secondary-950',
                    'link' => 'ref:primary-600',
                    'linkHover' => 'ref:primary-700',
                ],
                'typography' => [
                    'families' => [
                        [
                            'name' => 'Inter',
                            'role' => 'heading',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                        [
                            'name' => 'Inter',
                            'role' => 'body',
                            'source' => 'google',
                            'fallback' => 'system-ui, sans-serif',
                        ],
                    ],
                    'scale' => [
                        'xs' => '0.75rem',
                        'sm' => '0.875rem',
                        'base' => '1rem',
                        'lg' => '1.125rem',
                        'xl' => '1.25rem',
                        '2xl' => '1.5rem',
                        '3xl' => '1.875rem',
                        '4xl' => '2.25rem',
                        '5xl' => '3rem',
                    ],
                    'assignments' => [
                        'h1' => ['family' => 'heading', 'weight' => '700', 'size' => '2.5rem', 'style' => 'normal', 'lineHeight' => '1.2'],
                        'h2' => ['family' => 'heading', 'weight' => '600', 'size' => '2rem', 'style' => 'normal', 'lineHeight' => '1.25'],
                        'h3' => ['family' => 'heading', 'weight' => '600', 'size' => '1.5rem', 'style' => 'normal', 'lineHeight' => '1.3'],
                        'h4' => ['family' => 'heading', 'weight' => '500', 'size' => '1.25rem', 'style' => 'normal', 'lineHeight' => '1.35'],
                        'h5' => ['family' => 'heading', 'weight' => '500', 'size' => '1.125rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'h6' => ['family' => 'heading', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.4'],
                        'body' => ['family' => 'body', 'weight' => '400', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                        'link' => ['family' => 'body', 'weight' => '500', 'size' => '1rem', 'style' => 'normal', 'lineHeight' => '1.6'],
                    ],
                ],
                'borders' => [
                    'radius' => 'rounded-lg',
                    'imageRadius' => 'rounded-lg',
                ],
                'buttons' => [
                    'global' => [
                        'paddingX' => '1.5rem',
                        'paddingY' => '0.75rem',
                    ],
                    'primary' => [
                        'bg' => 'ref:primary-600',
                        'text' => 'ref:primary-50',
                        'border' => 'none',
                        'hoverBg' => 'ref:primary-700',
                        'hoverText' => 'ref:primary-50',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'sm',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'secondary' => [
                        'bg' => 'transparent',
                        'text' => 'ref:primary-600',
                        'border' => 'ref:primary-600',
                        'hoverBg' => 'ref:primary-600',
                        'hoverText' => 'ref:primary-50',
                        'hoverBorder' => 'ref:primary-600',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'sm',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                    'accent' => [
                        'bg' => 'ref:accent-500',
                        'text' => 'ref:secondary-950',
                        'border' => 'none',
                        'hoverBg' => 'ref:accent-500',
                        'hoverText' => 'ref:secondary-950',
                        'hoverBorder' => 'none',
                        'radius' => 'rounded-lg',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'hoverShadow' => 'md',
                        'hoverTransform' => 'lift',
                        'hoverOpacity' => '1',
                        'hoverDuration' => '300ms',
                        'hoverEasing' => 'ease-out',
                    ],
                ],
                'blockVariants' => [
                    [
                        'label' => 'Light',
                        'title' => 'ref:secondary-950',
                        'subtitle' => 'ref:secondary-800',
                        'paragraph' => 'ref:secondary-900',
                        'link' => 'ref:primary-600',
                        'linkHover' => 'ref:primary-700',
                        'list' => 'ref:secondary-900',
                        'hr' => 'ref:secondary-100',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:primary-50',
                        'buttonStyle' => 'primary',
                        'formBg' => 'ref:primary-50',
                        'formText' => 'ref:secondary-900',
                        'formLabel' => 'ref:secondary-950',
                        'formPlaceholder' => 'ref:secondary-400',
                        'formBorder' => 'ref:secondary-200',
                        'formBorderFocus' => 'ref:primary-600',
                        'formBorderError' => 'ref:accent-400',
                    ],
                    [
                        'label' => 'Accent',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:primary-100',
                        'paragraph' => 'ref:primary-200',
                        'link' => 'ref:accent-400',
                        'linkHover' => 'ref:accent-500',
                        'list' => 'ref:primary-200',
                        'hr' => 'rgba(255,255,255,0.2)',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:primary-600',
                        'buttonStyle' => 'accent',
                        'formBg' => 'rgba(255,255,255,0.1)',
                        'formText' => 'ref:primary-200',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:primary-100',
                        'formBorder' => 'rgba(255,255,255,0.3)',
                        'formBorderFocus' => 'ref:primary-50',
                        'formBorderError' => 'ref:accent-300',
                    ],
                    [
                        'label' => 'Dark',
                        'title' => 'ref:primary-50',
                        'subtitle' => 'ref:secondary-400',
                        'paragraph' => 'ref:secondary-200',
                        'link' => 'ref:primary-500',
                        'linkHover' => 'ref:primary-300',
                        'list' => 'ref:secondary-200',
                        'hr' => 'rgba(255,255,255,0.1)',
                        'paragraphBg' => 'transparent',
                        'blockBg' => 'ref:secondary-950',
                        'buttonStyle' => 'accent',
                        'formBg' => 'ref:secondary-950',
                        'formText' => 'ref:secondary-200',
                        'formLabel' => 'ref:primary-50',
                        'formPlaceholder' => 'ref:secondary-400',
                        'formBorder' => 'rgba(255,255,255,0.1)',
                        'formBorderFocus' => 'ref:primary-500',
                        'formBorderError' => 'ref:accent-400',
                    ],
                ],
            ],
            'menuConfig' => [
                'type' => 'megamenu',
                'megamenuSource' => 'native',
                'navPosition' => 'center',
                'animation' => 'none',
                'clickParentPage' => 'none',
                'clickParentPageNavbar' => false,
                'childLevels' => 3,
                'displayLogoDesktop' => true,
                'displayLogoMobile' => true,
                'displaySiteName' => false,
                'displaySocialMedia' => false,
                'transparentNavbar' => false,
                'colors' => [
                    'bg' => '#0f172a',
                    'text' => 'ref:secondary-100',
                    'textHover' => '#ffffff',
                    'secondBg' => '#1e293b',
                    'secondText' => '#cbd5e1',
                    'secondTextHover' => '#ffffff',
                    'thirdBg' => '#334155',
                    'thirdText' => '#94a3b8',
                    'divider' => 'rgba(255,255,255,0.1)',
                    'burgerOpen' => '#e2e8f0',
                    'burgerClose' => '#e2e8f0',
                    'socialMedia' => '#94a3b8',
                    'socialMediaHover' => '#ffffff',
                ],
            ],
            'blockStyles' => self::getDefaultBlockStyles(),
        ];
    }
}
